export const DEFAULT_TYPE_TO_CPN: Record<string, string> = {
  TEXT: "wkInput",
  TEXTAREA: "wkTextarea",
  SELECT: "wkSelect",
  CHECKBOX: "wkCheckboxGroup",
  RADIO: "wkRadioGroup",
  NUMBER_TEXT: "wkInputNumber",
  CURRENCY: "wkInputNumber",
  MOBILE: "wkInputNumber",
  FILE: "wkPickerFile",
  EMAIL: "wkInput",
  DATE: "wkDatePicker",
  TIME: "wkTimePicker",
  DATETIME: "wkDatePicker",
  WORD: "wkInput",
  ADMINISTRATION_REGION: "wkCascader",
  TABLE: "",
  CONTAINER: "",
  TAB: "",
  SEPARATOR: "",
  LOCATION: "wkLocation",
  RICHTEXT: "",
  BUTTON: "wkButton",
  SWITCH: "wkSwitch",
};
