// 类型与中文关系
export const CPN_TYPE_TO_NAME: Record<string, string> = {
  TEXT: "短文本",
  TEXTAREA: "长文本",
  SELECT: "选项",
  CHECKBOX: "复选框",
  RADIO: "单选",
  NUMBER_TEXT: "数字",
  CURRENCY: "金额",
  MOBILE: "手机号码",
  FILE: "文件",
  EMAIL: "邮箱",
  DATE: "日期",
  TIME: "时间",
  DATETIME: "日期时间",
  WORD: "静态文字",
  ADMINISTRATION_REGION: "地区",
  TABLE: "子表单",
  CONTAINER: "容器组件",
  TAB: "tab组件",
  SEPARATOR: "分割符",
  LOCATION: "定位",
  RICHTEXT: "富文本",
  BUTTON: "按钮",
  SWITCH: "开关",
};

// 布局组件无序映射
export const DEFAULT_TYPE_TO_CPN: Record<string, string> = {
  TEXT: "wkInput",
  TEXTAREA: "wkTextarea",
  SELECT: "wkSelect",
  CHECKBOX: "wkCheckboxGroup",
  RADIO: "wkRadioGroup",
  NUMBER_TEXT: "wkInputNumber",
  CURRENCY: "wkInputNumber",
  MOBILE: "wkMobile",
  FILE: "wkPickerFile",
  EMAIL: "wkInput",
  DATE: "wkDatePicker",
  TIME: "wkTimePicker",
  DATETIME: "wkDatePicker",
  WORD: "wkWord", // 邓雯，新写一个组件用于展示静态文案控件
  ADMINISTRATION_REGION: "wkCascader",
  TABLE: "wkSubTable",
  SEPARATOR: "wkSeparator", // 邓雯，新写一个组件用于展示分隔符控件
  LOCATION: "wkLocation",
  RICHTEXT: "wkRichText",
  BUTTON: "wkButton",
  SWITCH: "wkSwitch",
};

// 只需要字符串进行展示的控件
export const STRING_VALUE_TO_DISPLAY: string[] = [
  "TEXT",
  "TEXTAREA",
  "SELECT",
  "CHECKBOX",
  "RADIO",
  "NUMBER_TEXT",
  "CURRENCY",
  "MOBILE",
  "EMAIL",
  "DATE",
  "TIME",
  "DATETIME",
  "WORD",
  "ADMINISTRATION_REGION",
  "SWITCH",
];

export const CPN_TYPE_TO_ICON: Record<string, string> = {
  TEXT: "f-duanwenben",
  TEXTAREA: "f-changwenben1",
  SELECT: "f-xuanxiang1",
  RADIO: "f-danxuan1",
  NUMBER_TEXT: "f-shuzi1",
  CURRENCY: "f-jine1",
  CHECKBOX: "f-fuxuan",
  MOBILE: "f-shoujihaoma1",
  FILE: "f-wenjianshangchuan",
  EMAIL: "f-youxiang",
  DATE: "f-riqi1",
  TIME: "f-shijian1",
  DATETIME: "f-riqishijian1",
  WORD: "f-jingtaiwenzi1",
  ADMINISTRATION_REGION: "f-diqu1",
  TABLE: "f-zibiaoge",
  RICHTEXT: "f-fuwenben",
  LOCATION: "f-dingwei",
  CONTAINER: "f-rongqizujian",
  TAB: "f-tabzujian",
  SEPARATOR: "f-fengefu",
  DEFAULT: "f-kaifazhong",
};
